spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${DEV_MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui